<a href="https://colab.research.google.com/github/Maione-Anika-Reyes/58013-Linear-Algebra/blob/main/Laboratory_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

X = np.array([[1,1,1],
              [3,-2,-1],
              [-1,4,2]], dtype=float)

Y = np.array([[1],
              [4],
              [-3]],dtype=float)

print(X)
print("\n",X.shape)
print("\n",Y)
print("\n",Y.shape)

[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]

 (3, 3)

 [[ 1.]
 [ 4.]
 [-3.]]

 (3, 1)


Coding Activity 10

In [9]:
#Create a python program to solve for the price of flour per sack, yeast per pack,
#and one piece of egg.

from sympy import symbols, Eq, solve

x, y, z = symbols('x y z')

eq1 = Eq(30*x + 10*y + 120*z, 12500)
eq2 = Eq(40*x + 20*y + 200*z, 18000)
eq3 = Eq(50*x + 40*y + 360*z, 25700)

soln = solve((eq1, eq2, eq3), (x, y, z))

flour = soln[x]
yeast = soln[y]
egg = soln[z]

print("Price per sack of flour:",(flour),"pesos")
print("Price per pack of yeast:",(yeast),"pesos")
print("Price per egg:",(egg),"pesos")

Price per sack of flour: 330 pesos
Price per pack of yeast: 140 pesos
Price per egg: 10 pesos
