<a href="https://colab.research.google.com/github/Maione-Anika-Reyes/58013-Linear-Algebra/blob/main/Laboratory_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

A = np.array([[1,4],
              [0,3]])

np.linalg.det(A)

## Now other mathematics classes would require you to solve this by hand,
## and that is great for practicing your memorization and coordination skills
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([[1,3,5,6],
              [0,3,1,3],
              [3,1,8,2],
              [5,2,6,8]])
np.linalg.det(B)


-235.0000000000002

Associative Property

In [2]:
#Associative Property

import numpy as np

a = np.array([[0,3,1],
              [6,1,2],
              [3,2,0]])

b = np.array([[1,2,1],
              [7,2,0],
              [2,3,6]])

c = np.array([[1,5,0],
              [3,6,9],
              [2,4,6]])

Assoc1 = np.dot(np.dot(a,b),c)
Assoc2 = np.dot(a, np.dot(b,c))
print("Associative Property: \n")
print("Result 1:\n",Assoc1)
print("Result 2:\n",Assoc2)

Associative Property: 

Result 1:
 [[ 62 193 117]
 [113 277 288]
 [ 53 157 108]]
Result 2:
 [[ 62 193 117]
 [113 277 288]
 [ 53 157 108]]


Distributive Property

In [3]:
#Distributive Property

import numpy as np

a = np.array([[0,3,1],
              [6,1,2],
              [5,7,9]])

b = np.array([[1,2,1],
              [7,2,0],
              [2,3,6]])

c = np.array([[1,5,0],
              [3,6,9],
              [2,4,6]])

dstrb1 = np.dot(a,b,+c)
dstrb2 = np.dot(a,b) + np.dot(a,c)

print("Distributive Property\n")
print("Result 1: \n",dstrb1)
print("Result 2: \n",dstrb2)


Distributive Property

Result 1: 
 [[23  9  6]
 [17 20 18]
 [72 51 59]]
Result 2: 
 [[ 34  31  39]
 [ 30  64  39]
 [116 154 176]]


Scalar

In [6]:
#Scalar

import numpy as np

a = np.array([[0,3,1],
              [6,1,2],
              [5,7,9]])

b = np.array([[1,2,1],
              [7,2,0],
              [2,3,6]])

c = 6

s1 = c * np.dot(a,b)
s2 = np.dot(c * a,b)

print("Scalar:\n")
print("Result 1:\n",s1)
print("Result 2:\n",s2)

Scalar:

Result 1:
 [[138  54  36]
 [102 120 108]
 [432 306 354]]
Result 2:
 [[138  54  36]
 [102 120 108]
 [432 306 354]]


Commutative Property

In [7]:
#Commutative Property

import numpy as np

a = np.array([[0,3,0],
              [2,2,2],
              [1,3,1]])

b = np.array([[4,0,3],
              [1,1,1],
              [0,3,2]])

c1 = np.dot(a,b)
c2 = np.dot(b,a)

print("Commutative Property:\n")
print("Result 1:\n",c1)
print("Result 2:\n",c2)

Commutative Property:

Result 1:
 [[ 3  3  3]
 [10  8 12]
 [ 7  6  8]]
Result 2:
 [[ 3 21  3]
 [ 3  8  3]
 [ 8 12  8]]


Identity Matrix

In [9]:
#Identity Matrix

import numpy as np

a = np.array([[0,3,0],
              [2,2,2],
              [1,3,1]])

i = np.identity(3)
IM = np.dot(i,a)

print("Identity Matrix:\n",IM)

Identity Matrix:
 [[0. 3. 0.]
 [2. 2. 2.]
 [1. 3. 1.]]


Zero Matrix

In [10]:
#Zero Matrix

import numpy as np

a = np.array([[0,3,0],
              [2,2,2],
              [1,3,1]])

z = np.zeros((3,3))
zm = np.dot(z,a)

print("Zero Matrix:\n",z)

Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
