<a href="https://colab.research.google.com/github/Maione-Anika-Reyes/58013-Linear-Algebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1:

In [12]:
#1

import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[1,2],
              [3,4],
              [5,6]])

c = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

d = np.array([[1,2],
              [3,4]])

print('a.AB:')
print(np.dot(a,b))

print('\nb.D + D:')
print(np.add(d,d))

print('\nc.2C:')
print(2*c)

a.AB:
[[22 28]
 [49 64]]

b.D + D:
[[2 4]
 [6 8]]

c.2C:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Problem 2:

In [11]:
#2

import numpy as np

a = np.array([2, 7, 4])
b = np.array([3, 9, 8])

print("A • B: ")
print(np.cross(a,b))

A • B: 
[20 -4 -3]
