<a href="https://colab.research.google.com/github/Maione-Anika-Reyes/58013-Linear-Algebra/blob/main/Prelim_Examination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
#Question 1. (20 points) Create a Multiplication Table/Chart of 1 to 10 using numpy/ python program.


import numpy as np

def mtable(n):
    range = np.arange(1, n+1)
    return range * range[:, None]

print(mtable(10)*2)



[[  2   4   6   8  10  12  14  16  18  20]
 [  4   8  12  16  20  24  28  32  36  40]
 [  6  12  18  24  30  36  42  48  54  60]
 [  8  16  24  32  40  48  56  64  72  80]
 [ 10  20  30  40  50  60  70  80  90 100]
 [ 12  24  36  48  60  72  84  96 108 120]
 [ 14  28  42  56  70  84  98 112 126 140]
 [ 16  32  48  64  80  96 112 128 144 160]
 [ 18  36  54  72  90 108 126 144 162 180]
 [ 20  40  60  80 100 120 140 160 180 200]]


In [58]:
#Question 2. (10 points) In relation to Question 1, show a solution that doubles all the values of each element.

import numpy as np

def mtable(n):
    range = np.arange(1, n+1)
    return range * range[:, None]

print(mtable(10)*2)



[[  2   4   6   8  10  12  14  16  18  20]
 [  4   8  12  16  20  24  28  32  36  40]
 [  6  12  18  24  30  36  42  48  54  60]
 [  8  16  24  32  40  48  56  64  72  80]
 [ 10  20  30  40  50  60  70  80  90 100]
 [ 12  24  36  48  60  72  84  96 108 120]
 [ 14  28  42  56  70  84  98 112 126 140]
 [ 16  32  48  64  80  96 112 128 144 160]
 [ 18  36  54  72  90 108 126 144 162 180]
 [ 20  40  60  80 100 120 140 160 180 200]]


In [6]:
#Question 3. (10 points) Create a square matrix that has a diagonal 1's.

import numpy as np

A = np.eye(3,3)
print(A)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [57]:
#Question 4. (30 points) Create a matrix whose elements are:

import numpy as np

matrix = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])
print(matrix.shape)
print(matrix.size)
print(matrix.ndim)

(3, 4)
12
2


In [50]:
#Question 5. (30 points) Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element.

import numpy as np

arrayOne = np.array([[5,6,9],[21,18,27]])
arrayTwo = np.array([[15,33,24],[4,7,1]])

print("A + B:")
print(np.add(arrayOne, arrayTwo))

c = (arrayOne**2)
d = (arrayTwo**2)
print("\nSquare of each element: ")
print("Array One: \n",c)
print("\nArray Two:\n",d)


A + B:
[[20 39 33]
 [25 25 28]]

Square of each element: 
Array One: 
 [[ 25  36  81]
 [441 324 729]]

Array Two:
 [[ 225 1089  576]
 [  16   49    1]]
