<a href="https://colab.research.google.com/github/Maione-Anika-Reyes/58013-Linear-Algebra/blob/main/Vectors%2C_Spaces%2C_and_Operators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#Size Dimension, Size

import numpy as np
ball1 = np.array([1,2,3])
ball2=np.array([0,1,-1])
print(ball1)
print(ball2)

#ball = np.shape([[ball1],[ball2]])
ball=np.shape(ball1)
balls=np.shape(ball2)
z=ball+balls
print(z)

[1 2 3]
[ 0  1 -1]
(3, 3)


In [12]:
#addition

import numpy as np
a=np.array([4,3])
b=np.array([2,-5])
r=a+b
print(r)

[ 6 -2]


In [15]:
#subtraction

import numpy as np
r1=np.subtract(a,b)
print(r1)
r2=np.subtract(b,a)
print(r2)

[2 8]
[-2 -8]


In [16]:
from numpy.core import arrayprint
#scalar product

s = np.array([2])
v = s*a
print(v)

[8 6]


In [18]:
#dot product

import numpy as np
a = np.array([4,3])
b = np.array([[2],[-5]])
print(b*a)

[[  8   6]
 [-20 -15]]


In [33]:
#property of matrix

#identity matrix
c = np.eye(3,3)
print(c)

#zero matrix
d = np.zeros([5,5],)
print("\n",d)

#full matrix
e = np.full([3,3],7)
print("\n",e)

#transpose matrix
f = np.transpose(a)
print("\n",f)

#empty matrix
c = np.empty([2,2])
print("\n",c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 [[7 7 7]
 [7 7 7]
 [7 7 7]]

 [4 3]

 [[1. 0.]
 [0. 1.]]
